### ISSUE TITLE
Property annotation around promoted property does not work anymore

### ISSUE THREAD

**Issue by bronek89** [zircote/swagger-php#1031]
Hi:) Thank you for this very helpful library!

Since version 4.0 Property annotation around promoted property does not work anymore (on php 8.0)

Code example:

```php
<?php declare(strict_types=1);

use OpenApi\Annotations as OA;

/**
 * @OA\Schema()
 */
final class Foo
{
    /**
     * @OA\Property(description="bar")
     */
    public int $bar;

    public function __construct(
        /**
         * @OA\Property(description="baz")
         */
        public int $baz,
    ) {
    }
}
```

Result from version 3.3.2

```yaml
components:
  schemas:
    Foo:
      properties:
        bar:
          description: bar
          type: integer
        baz:
          description: baz
          type: integer
      type: object
```
 
Result from 4.0.4:

```yaml
components:
  schemas:
    Foo:
      properties:
        bar:
          description: bar
          type: integer
      type: object
```
