### ISSUE TITLE
Support Enum as type hints

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#1056]
Follow up from #1050

I tried to use it in a Schema like this:
```
#[Schema]
class BlogPost {
    public function __construct(
        #[Property] public int $id,
        #[Property] public string $content,
        #[Property] public Status $status,
    ) {}
}
```
which generates:
```
components:
  schemas:
    BlogPost:
      properties:
        id:
          type: integer
        content:
          type: string
        status: {  }         # <-- should be $ref: '#/components/schemas/Status'
      type: object
    Status:
      type: string
      enum:
        - DRAFT
        - PUBLISHED
        - ARCHIVED
```
Here $status in BlogPost should be inferred as a reference to #/components/schemas/Status

Manually setting ref works:
```
class BlogPost {
    public function __construct(
        #[Property] public int $id,
        #[Property] public string $content,
        #[Property(ref: "#/components/schemas/Status")] public Status $status, # <-- works
    ) {}
}
```
In a similar manner, I tried doing this:
```
enum Fizz {
    case FOO;
    case BAR;
    case BAZ;
}

#[Schema]
class Buzz {
    public function __construct(
        #[Property] public int $id,
        #[Property] public Fizz $fizz,
    ) {}
}
```
Which Generates:
```
components:
  schemas:
    Buzz:
      properties:
        id:
          type: integer
        fizz: {  }
      type: object
```
Should Generate:
```
components:
  schemas:
    Buzz:
      properties:
        id:
          type: integer
        fizz:
          type:string
          enum:
            - FOO
            - BAR
            - BAZ
      type: object
```
