### ISSUE TITLE
Version is only available reliably for validation and serialization

### ISSUE THREAD

**Issue by igordeveloper** [zircote/swagger-php#1213]
I'm receiving the message below to generate openapi documentation using the NelmioApiDocBundle, after the release 4.2.14 of swagger-php bundle.

**Version is only available reliably for validation and serialization**

Below nelmio config:
```
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
        - ^/[a-z]
    documentation:
        openapi : 3.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
```

I have tried set the openapi version using **Generator::setVersion()** too and the error persist.

Used versions bundle:
```
nelmio/api-doc-bundle               v4.8.2
zircote/swagger-php                 4.3.0
```

Is there any missing configuration to inform the openapi version?

Thank you.
igor.
