### ISSUE TITLE
Different state of real class properties and schema properties: nullable

### ISSUE THREAD

**Issue by dmitrach** [zircote/swagger-php#1318]
Hello. Thank you for your package, it has saved some my time due to existent documentation in classes. 

But I found a feature or a bug) when the real properties of a class are different with schema properties. 

**Steps to reproduce**

I have the next code.

```php
    /**
     * Some description.
     *
     * @OA\Property(nullable=false, format="number", example="0.00")
     */
    public ?string $value = null;
```

It describes the value that has the default value `null`, but this value is never returned in responses and there is always non-null values, like *0.00*.

I expected the follow description in *yaml*. There is `nullable: false` or without `nullable` due to I redefine this property.

```yml
      properties:
        annual:
          description: 'Some description.'
          type: string
          nullable: false # here
          format: number
          example: '0.00'
```

or

```yml
      properties:
        annual:
          description: 'Some description.'
          type: string # there isn't nullable here
          format: number
          example: '0.00'
```

But I got the follow result.

```yml
      properties:
        annual:
          description: 'Some description.'
          type: string
          nullable: true # here
          format: number
          example: '0.00'
```

To fix it I've redefined the value type: `type="string"`.

```php
    /**
     * Some description.
     *
     * @OA\Property(type="string", format="number", example="0.00")
     */
    public ?string $value = null;
```

Now I got this result.

```yml
      properties:
        annual:
          description: 'Some description.'
          type: string # there isn't nullable here, because I defined another type.
          format: number
          example: '0.00'
```

I would like to know, it is a bug or a feature? Perhabs the tool should override the detected state of the property. 

Thank you!
