### ISSUE TITLE
Support multiline description

### ISSUE THREAD

**Issue by dmitrach** [zircote/swagger-php#1319]
I've have a long description, there is more 120 characters in a line and it is a problem for reading and for PHP CS Fixer. 

I would like to divide the line into multiple lines. Currently I cannot do it due to extra symbols like `*` of a multiline comment. Also it cannot work with markdown, for example, a list. 

```php
/*
 * @OA\Schema(
 *   schema="AuthorizationStatus",
 *   type="integer",
 *   description=">
 *     An authorization status: 
 *     - 1 - registration isn't finished, 
 *     - 2 - a user has an active booking, 
 *     - 3 - a user has been registered without an active booking.",
 *   enum={1, 2, 3},
 *   example=1
 * )
 */
```

The current result.

```yml
description: ">\n *   An authorization status:\n *   - 1 - registration isn't finished,\n *   - 2 - a user has an active booking, \n *   3 - a user has been registered without an active booking."
```

Expected.

```yml
description: >
  An authorization status:
  - 1 - registration isn't finished,
  - 2 - a user has an active booking, 
  - 3 - a user has been registered without an active booking.
```

As a result I've removed `*` from comments to get the desired result.

```php
/*
 * @OA\Schema(
 *   schema="AuthorizationStatus",
 *   type="integer",
 *   description=">
An authorization status: 
- 1 - registration isn't finished, 
- 2 - a user has an active booking, 
- 3 - a user has been registered without an active booking.",
 *   enum={1, 2, 3},
 *   example=1
 * )
 */
```
