### ISSUE TITLE
[HELP]How to use custom key in Property?

### ISSUE THREAD

**Issue by 3lang3** [zircote/swagger-php#1336]
I want to set `x-faker` key in property. Tried many methods and finally failed.

This is the result I hope to get.

```yaml
Pet:
  type: object
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
      x-faker: name.firstName # LOOK THIS!
      example: doggie
    photoUrls:
      type: array
      items:
        type: string
        x-faker: image.imageUrl
```
