### ISSUE TITLE
Add support for .openapi config file

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#1361]
This could be a good place to configure additional processors that are not just appended, etc.

**Comment by DerManoMann** [comment]
Using `\Composer\Factory::getComposerFile() ` to get the root directory...

**Comment by DerManoMann** [comment]
Might need option to override on the CL.

**Comment by DerManoMann** [comment]
Draft of a fully fleshed out file:
```yaml
generator:
  version: 3.0.0
  validate: true
  analyser:
    class: 'OpenApi\\Analysers\\ReflectionAnalyser'
  logger:
    class: 'OpenApi\\Loggers\\DefaultLogger'
  aliases:
    replace: false
    map:
      oax: 'Radebatz\\OpenApi\\Extras\\Annotations'
  namespaces:
    replace: false
    list:
      - 'Radebatz\\OpenApi\\Extras\\Annotations\\'

processors:
  - class: 'Radebatz\\OpenApi\\Extras\\Processors\\MergeControllerDefaults'
    before: 'OpenApi\\Processors\\BuildPaths'
    key: 'mergeControllerDefaults'
  - class: 'OpenApi\\Processors\\OperationId'
    replace: 'Radebatz\\OpenApi\\Extras\\Processors\\MyOperationId'
    key: 'myOperationId'
  - class: 'Radebatz\\OpenApi\\Extras\\Processors\\MergeControllerDefaults'
    remove: true
  - key: operationId
    config:
      hash: false
```
