### ISSUE TITLE
Add a default parameter for parameters

### ISSUE THREAD

**Issue by stollr** [zircote/swagger-php#1479]
OpenApi allows the specification of default values for optional parameters (see [here](https://swagger.io/docs/specification/describing-parameters/#default)).

This would be a useful addition to this library.

**Comment by DerManoMann** [comment]
This already exists. If you look closer you'll see that the default is not set on the property directly, but on the property schema (`default: 0`):
```yaml
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
          description: The number of items to skip before starting to collect the result set.
```
