### ISSUE TITLE
Defining components

### ISSUE THREAD

**Issue by waghanza** [zircote/swagger-php#619]
Hi @bfanger ,

I want to define custom component (so I can re-use them in several definitions).

I didn't find any example on how to deal with it.

How can I add the following definitions from my `php` **source** ?

```yaml
components:
  parameters:
    page:
      in: query
      name: page
      required: false
      schema:
        type: integer
 ```

Regards,
