### ISSUE TITLE
x-tagGroups

### ISSUE THREAD

**Issue by apausepi** [zircote/swagger-php#696]
Hello, 

Is it possible to use x-tagGroups ?
It's a x element but on root. So I don't know how add it.

**Comment by bfanger** [comment]
OA\OpenApi(x={tagGroups="value"})

**Comment by zl-kolev** [comment]
Now I get this error: trigger_error("[Semantical Error] Couldn't find constant tagGroups.

Can you briefly point me in the right direction, please?

**Comment by bfanger** [comment]
Ah, tagGroups needed to be quoted inside the object literal. I've updated the code in my previous answer.

**Comment by zl-kolev** [comment]
@bfanger, I have some progress on that matter, but I'm still struggling to get it to work exactly how I intend. Unfortunately, there is so little info out there and it's all written in `json` or `yaml`. It's rather a pain trying to "reverse engineer" a `.yaml` file to get the desired annotations.

I'm trying to achieve this:
```yaml
x-tagGroups:
  - name: User Management
    tags:
      - Users
      - API keys
      - Admin
```
With this:
```
@OA\OpenApi(
    x={
        "tagGroups"=
            {"name"="User Management", "tags"={"Users", "API keys", "Admin"}
        },
    }
),
```
And I get this (note the missing dash before `name`):
```yaml
x-tagGroups:
  name: User Management
  tags:
    - Users
    - API keys
    - Admin
```
What am I missing?
