### ISSUE TITLE
Nullable property

### ISSUE THREAD

**Issue by xLs51** [zircote/swagger-php#705]
For the following property : 

```
/**
 * The ID.
 * @OA\Property()
 * @var int|null
 */
private $id;
```

I would expect : 

```
properties:
  id:
    description: 'The ID.'
    type: integer
    nullable: true
  type: object
```

But I get : 

```
properties:
  id:
    description: 'The ID.'
    type: integer
  type: object
```

I can of course fix it by adding `@OA\Property(nullable=true)`, but couldn't this be done automatically?
