### ISSUE TITLE
How to generate property with mixed types?

### ISSUE THREAD

**Issue by Sufir** [zircote/swagger-php#731]
I need something like that:
```
type: array
items:
  oneOf:
    - type: string
    - type: integer
```

And that 
```
 *       @OA\Property(
 *          property="config",
 *          type="array",
 *          items={}
 *       )
```
generates invalid
```
"config": {
        "type": "array",
         "items": []
}
```
I need:
```
"config": {
        "type": "array",
         "items": {}
}
```

**Comment by wapmorgan** [comment]
You can wrap all it in `oneOf`:
```yaml
oneOf:
 - type: array
   items:
     type: string
 - type: array
   items:
     type: integer
```
