### ISSUE TITLE
Using SchemaDefinition within a description alongside x-displayName in tags

### ISSUE THREAD

**Issue by zl-kolev** [zircote/swagger-php#784]
I'm trying to create a documentation page where each tag's description includes a `SchemaDefinition` and some markdown similar to the models section of [ReDoc Pet Store](http://redocly.github.io/redoc/#tag/pet_model). I have examined the `yaml` [structure of the Pet Store](http://redocly.github.io/redoc/openapi.yaml) and it sems to me the snippet I'm interested in is this one:

```
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
  - name: pet_model
    x-displayName: The Pet Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Pet" />
  - name: store_model
    x-displayName: The Order Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Order" exampleRef="#/components/examples/Order" showReadOnly={true} showWriteOnly={true} />
```

1. So, is it possible to hook a `SchemaDefinition` **_and_** markdown to a description attribute using OpenAPI annotations? How does that look in terms of OpenAPI annotations?

```
     @OA\Schema(
         schema="Order",
         ref="#/components/schemas/Order",
         type="object",
         @OA\Property(property="a"),
         @OA\Property(property="b"),
         @OA\Property(property="c", allOf={
             @OA\Schema(
                 @OA\Property(property="d"),
                 @OA\Property(property="e"),
                 @OA\Property(property="f")
             )
             *** 2 more nested Schema objects ***
         }),
     )
```

2. How to properly name and reference my `@OA\Schema` object to be able to point to it in any description attribute as shown in the first snippet?

Note that the schema is deeply nested and I need the top level parent with all children. If I manually add a `SchemaDefinition` to my `yaml` file, I only get `object Order Recursive` (using [redoc](https://github.com/Redocly/redoc) to render the `yaml`) so it seems to me I'm doing something wrong with the `schema` and `ref` attributes.

Thanks in advance, hope this is useful to a wider audience!
