### ISSUE TITLE
Examples tag not work under Parameter, MediaType when generate yaml

### ISSUE THREAD

**Issue by acroscp** [zircote/swagger-php#869]
```
/**
 * @OA\Response(
 *     response=200,
 *     description="",
 *     @OA\MediaType(
 *          mediaType="application/json",
 *          type="object",
 *          @OA\Schema(
 *          @OA\Property(property="name", type="integer", description="demo")
 *       ),
 *          @OA\Examples(example=200,value={"name":1}),
 *          @OA\Examples(example=300,value={"name":1}),
 *          @OA\Examples(example=400,value={"name":1})
 *     ),
 *   )
 */

```
expect

```
              examples:
                '200':
                  value: { name: 1 }
                '300':
                  value: { name: 21 }
                '400':
                  value: { name: 13 }
```
but get

```
              examples:
                -
                  example: 200
                  value: { name: 1 }
                -
                  example: 300
                  value: { name: 21 }
                -
                  example: 400
                  value: { name: 13 }

```
src/Annotations/MediaType.php
src/Annotations/Parameter.php

**need to fix**
current
```
public static $_nested = [
        Schema::class => 'schema',
        Examples::class => ['examples'],
    ];
```
to
```
public static $_nested = [
        Schema::class => 'schema',
        Examples::class => ['examples', 'example'],
    ];
```
