### ISSUE TITLE
Default parameter is added (Swagger UI does not work)

### ISSUE THREAD

**Issue by MelingRu** [zircote/swagger-php#878]
Annotation
```php
     * @OA\Get(
     *     path="/user/{id}",
     *     summary="Retrieve User",
     *     description="Retrieve User",
     *     tags={"User"},
     *     @OA\Parameter(ref="#/components/parameters/Identifier"),
     *     @OA\Response(
     *          response="200",
     *          description="User Entity",
     *          @OA\JsonContent(ref=@Model(type=User::class, groups={"userForm"})),
     *     )
     * )
```
Config
```yaml
nelmio_api_doc:
    documentation:
        components:
            parameters:
                Identifier:
                    name: id
                    in: path
                    description: Entity Identifier
                    schema:
                        type: integer
                        pattern: \d+
```

Result
```json
{
    "/user/{id}": {
        "get": {
            "tags": [
                "User"
            ],
            "summary": "Retrieve User",
            "description": "Retrieve User",
            "operationId": null,
            "parameters": [
                {
                    "$ref": "#/components/parameters/Identifier"
                },
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "User Entity",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                },
            }
        }
    }
}
```

In result identifier was added twice, as referenced parameter and as default parameter (string)

When i click "Try it out", fill id and "Execute", i get error in field "Required field is not provided"
