### ISSUE TITLE
Reading examples from files

### ISSUE THREAD

**Issue by SirRFI** [zircote/swagger-php#973]
Greetings,

OpenAPI3 YAML allows to read JSON and other files as examples, like so:
```yaml
schema: (...)
examples:
    - externalValue: ./responses/examples/1.json
    - externalValue: ./responses/examples/2.json
    - externalValue: ./responses/examples/3.json
```
Where the path is relative to documentation's location or the main specification file, unsure.

Is it possible to read example files using this library, but from any location in the project (not exposed by webserver)? This would allow to easily reuse samples from tests, rather than duplicating them somewhere in public directory.
