### ISSUE TITLE
Empty array is generated instead of empty object

### ISSUE THREAD

**Issue by simivar** [zircote/swagger-php#988]
With a definition like below:

```php
/**
 * @OA\Schema(
 *     schema="SomeSchemaHere",
 *     type="object",
 *
 *     @OA\Property(
 *         property="data",
 *         type="object",
 *
 *         example={
 *             "type": "ok",
 *             "attributes": {}
 *         },
 *
 *         @OA\Property(
 *             property="type",
 *             type="string"
 *         ),
 *
 *         @OA\Property(
 *             property="attributes",
 *             type="object"
 *         )
 *     )
 * )
```

an invalid YAML file is generated with `[]` in examples instead of empty object `{}`
```yaml
SomeSchemaHere:
      properties:
        data:
          properties:
            type:
              type: string
            attributes:
              type: object
          type: object
          example:
            type: ok
            attributes: []
      type: object
```
